name: Build and release
on: push

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        id: setup_go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14"

      - name: Execute tests
        id: tests
        shell: bash
        run: go test ./...
